# ISSF - Information System on Small Scale Fisheries
# Author: Joshua Murphy
# Date: December 23rd, 2018
# https://github.com/toobigtoignore/issf

# Docker Compose file to orchestrate the containers needed to run ISSF
# as well as a PostgreSQL/PostGIS database

version: '3'

services:
  web:
    image: tbti/web:2.0 
    #build: "."
    #command: "/bin/bash -c 'yes'"
    command: "/bin/sh -c 'python manage.py collectstatic --noinput && gunicorn issf_prod.wsgi -b 0.0.0.0:80'"
    restart: always
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=issf_prod.settings
    volumes:
      - "./:/issf:Z"
      - "./static:/static:Z"
    expose:
      - 80
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  db:
    image: mdillon/postgis:9.5-alpine
    expose:
      - 5432
    restart: always
    volumes:
      - "./scripts:/scripts:Z"
      - "./data/postgres:/data/postgres/:Z"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
  nginx:
    image: nginx:alpine
    expose:
      - 80
    depends_on:
      - web
    restart: always
    volumes:
      - "./:/src:Z"
      - "./data/nginx:/etc/nginx/conf.d:Z"
      - "./static:/static:Z"
      - "./user_uploads:/user_uploads:Z"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: issfcloud.toobigtoignore.net, www.issfcloud.toobigtoignore.net"
      traefik.port: 80
      traefik.frontend.entryPoints: "https"
  traefik:
    image: traefik:1.7 # The official Traefik docker image
    ports:
      - "80:80"     # The HTTP port
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./data/traefik/traefik.toml:/traefik.toml
      - ./data/traefik:/traefik_data/
